# Config schema for date range, you can find the implementation in
# Drupal\facets_date_range\Plugin\facets\widget\DateRangeWidget.
facet.widget.config.date_range:
  type: facet.widget.default_config
  label: 'Date Range widget configuration'
